GET http://localhost:3000/lists

###
POST http://localhost:3000/lists 
Content-Type: application/json

{
    "name" : "My List"
}

###
GET http://localhost:3000/lists/10

###
GET  http://localhost:8000/lists